version: 0.2
env:
  variables:
    AWS_S3_NAME: "digital-qa"
    AWS_S3_REGION: "us-east-1"
phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - echo Installing Bundler...
      - gem install bundler
      - bundle install
  pre_build:
    commands:
      - ruby --version
  build:
    commands:
     - mkdir ./reports
     - cucumber --format html --out .reports/reports.html
reports:
  new-report-group:
    files:
      - './reports/*.html'
    base-directory: './reports'
    #file-format: CUCUMBERJSON