version: 0.2
env:
  variables:
    AWS_S3_NAME: "digital-qa"
    AWS_S3_REGION: "us-east-1"
phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - echo Installing cucumber....
      - gem install cucumber:3.1.0
      - gem install rspec:3.7.0
  pre_build:
    commands:
      - cucumber --version
      - ruby --version
  build:
    commands:
     - mkdir ./reports && cd ./reports
     - cucumber --format json --out report.json

  post_build:
    commands:
     - mkdir ./temp && cd ./temp &&
     - cucumber --format html --out report.html
     - aws s3 sync ./*.html s3://$AWS_S3_NAME --acl public-read --region $AWS_S3_REGION
reports:
  new-report-group:
    files:
      - './*.json'
    base-directory: './reports'
    file-format: CUCUMBERJSON