version: 0.2
env:
  variables:
    AWS_S3_NAME: "digital-qa"
    AWS_S3_REGION: "us-east-1"
phases:
  install:
    runtime-versions:
      ruby: 2.6
    commands:
      - echo Installing cucumber....
      - gem install cucumber:3.1.0
      - gem install rspec:3.7.0
  pre_build:
    commands:
      - cucumber --version
      - ruby --version
  build:
    commands:
     - mkdir ./temp
     - cucumber --format json --out ./temp/report.json
  post_build:
    commands:
     - mkdir ./temp
     - cucumber --format html --out ./temp/report.html
     - aws s3 sync ./temp/*.html s3://$AWS_S3_NAME --acl public-read --region $AWS_S3_REGION
reports:
  new-report-group:
    files:
      - './*.json'
    base-directory: './temp'
    file-format: CUCUMBERJSON