version: 0.2
env:
  variables:
    AWS_S3_NAME: "digital-qa"
    AWS_S3_REGION: "us-east-1"
phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - echo Installing dependencies....
     # - gem install bundler
      #- bundle install
      - gem install cucumber:3.1.0
      - gem install rspec:3.7.0
      - gem install httparty:0.18.1
  pre_build:
    commands:
      - echo version ....
      - cucumber --version
      - ruby --version
  build:
    commands:
    -  echo reporting generation....
    - mkdir ./temp
    - cucumber
  post_build:
    commands:
     - echo push report to s3....
     - cucumber --format html --out ./temp/report.html
     - aws s3 cp ./temp/*.html s3://$AWS_S3_NAME --acl public-read --region $AWS_S3_REGION
reports:
  new-report-group:
    files:
      - './*.json'
    base-directory: './temp'
    file-format: CUCUMBERJSON